"""Ghost configuration + encrypted API-key storage.

Single-user product (Phase plan locked in single-user). A single
`ghost_settings` row holds the active provider, model, monthly cap, and
the encrypted API key.

Encryption: Fernet symmetric using a key derived from the env-var
GHOST_SECRET (Fernet key, generated by `Fernet.generate_key()` and put
in .env). If the secret is missing the key is stored in plaintext with
a warning -- acceptable for local dev, never for hosted deploy.
"""

import datetime as dt
import logging
import os
from typing import Any, Optional

import storage

logger = logging.getLogger(__name__)

VALID_MODES = {"hosted", "local"}
VALID_PROVIDERS = {"anthropic", "openai", "custom"}

DEFAULT_MONTHLY_CAP_USD = 50.0


def _fernet():
    """Return a Fernet cipher if GHOST_SECRET is set, else None."""
    secret = os.environ.get("GHOST_SECRET")
    if not secret:
        return None
    try:
        from cryptography.fernet import Fernet

        return Fernet(secret.encode())
    except Exception:
        logger.exception("cryptography.Fernet init failed; falling back to plaintext")
        return None


def init() -> None:
    """Create the ghost_settings table with a single fixed-id row."""
    conn = storage._get_conn()
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS ghost_settings (
            id              INTEGER PRIMARY KEY CHECK (id = 1),
            mode            TEXT NOT NULL DEFAULT 'hosted',
            provider        TEXT NOT NULL DEFAULT 'anthropic',
            api_key_enc     TEXT,
            api_key_plain   TEXT,
            model           TEXT NOT NULL DEFAULT 'claude-opus-4-7',
            monthly_cap_usd REAL NOT NULL DEFAULT 50.0,
            base_url        TEXT,
            updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        )
        """
    )
    conn.execute(
        "INSERT OR IGNORE INTO ghost_settings (id) VALUES (1)"
    )
    conn.commit()


def _now_iso() -> str:
    now = dt.datetime.now(dt.timezone.utc)
    return now.strftime("%Y-%m-%dT%H:%M:%S.") + f"{now.microsecond // 1000:03d}Z"


def get() -> dict[str, Any]:
    """Return current settings sans plaintext key."""
    conn = storage._get_conn()
    import sqlite3 as _sqlite3

    conn.row_factory = _sqlite3.Row
    row = conn.execute("SELECT * FROM ghost_settings WHERE id = 1").fetchone()
    conn.row_factory = None
    if row is None:
        return {"mode": "hosted", "provider": "anthropic", "model": "claude-opus-4-7"}
    d = dict(row)
    # Never leak the actual key; surface only whether one is configured.
    has_key = bool(d.get("api_key_enc") or d.get("api_key_plain"))
    d.pop("api_key_enc", None)
    d.pop("api_key_plain", None)
    d["api_key_set"] = has_key
    return d


def update(
    *,
    mode: Optional[str] = None,
    provider: Optional[str] = None,
    api_key: Optional[str] = None,
    model: Optional[str] = None,
    monthly_cap_usd: Optional[float] = None,
    base_url: Optional[str] = None,
) -> dict[str, Any]:
    """Update one or more fields. Pass api_key="" to clear it."""
    if mode is not None and mode not in VALID_MODES:
        raise ValueError(f"Invalid mode: {mode!r}")
    if mode == "local":
        raise ValueError(
            "Local Ghost is not yet available; switch to 'hosted' in settings."
        )
    if provider is not None and provider not in VALID_PROVIDERS:
        raise ValueError(f"Invalid provider: {provider!r}")

    conn = storage._get_conn()
    fields: dict[str, Any] = {}
    if mode is not None:
        fields["mode"] = mode
    if provider is not None:
        fields["provider"] = provider
    if model is not None:
        fields["model"] = model
    if monthly_cap_usd is not None:
        fields["monthly_cap_usd"] = float(monthly_cap_usd)
    if base_url is not None:
        fields["base_url"] = base_url
    if api_key is not None:
        f = _fernet()
        if api_key == "":
            fields["api_key_enc"] = None
            fields["api_key_plain"] = None
        elif f is not None:
            fields["api_key_enc"] = f.encrypt(api_key.encode()).decode()
            fields["api_key_plain"] = None
        else:
            logger.warning(
                "GHOST_SECRET not set; storing api_key in plaintext. "
                "Set GHOST_SECRET (a Fernet key) to enable encryption."
            )
            fields["api_key_plain"] = api_key
            fields["api_key_enc"] = None

    if not fields:
        return get()
    fields["updated_at"] = _now_iso()
    sets = ", ".join(f"{k} = ?" for k in fields)
    conn.execute(
        f"UPDATE ghost_settings SET {sets} WHERE id = 1",
        list(fields.values()),
    )
    conn.commit()
    return get()


def get_api_key() -> Optional[str]:
    """Decrypt and return the API key, or None."""
    conn = storage._get_conn()
    row = conn.execute(
        "SELECT api_key_enc, api_key_plain FROM ghost_settings WHERE id = 1"
    ).fetchone()
    if row is None:
        return None
    enc, plain = row
    if enc:
        f = _fernet()
        if f is None:
            logger.error(
                "api_key_enc present but GHOST_SECRET is missing; cannot decrypt"
            )
            return None
        try:
            return f.decrypt(enc.encode()).decode()
        except Exception:
            logger.exception("Failed to decrypt api_key")
            return None
    return plain
